### ISSUE TITLE
Won't work on RPi3-B

### ISSUE THREAD

**Issue by bo01ean** [golemparts/blinkt#1]
I am having trouble getting this to work on the Raspberry Pi 3-B.

Any suggestions?

**Comment by golemparts** [comment]
I have it running on a 3B without any issues with the latest Raspbian release. Are you using Raspbian Jessie and the latest stable Rust (1.12.1)? Does running the examples panic with any errors? Do the original Pimoroni Python examples work for you?

Any details you can provide would be appreciated.

**Comment by golemparts** [comment]
Also, do you have Blinkt configured for the appropriate number of APA102's, and the right data/clock pins? By default, the new() method sets it up for the Pimoroni Blinkt! board with 8x APA102, data on GPIO 23 and clock on GPIO 24. You can use with_settings() to specify a different number of APA102's, and manually select the data and clock pins.

A snippet of the code that isn't working would be helpful as well.

**Comment by bo01ean** [comment]
I am using 2016-05-27-raspbian-jessie-loverpi with the default MISO/CLK pins:

```extern crate rand;
extern crate blinkt;

use std::thread;
use std::time::Duration;
use rand::Rng;

const DAT: u8 = 21;
const CLK: u8 = 23;
const NUM_PIXELS: usize = 8;

use blinkt::Blinkt;

fn main() {
    let mut rng = rand::thread_rng();
// Main mod
    let mut blinkt = Blinkt::with_settings(DAT, CLK, NUM_PIXELS).unwrap();
    blinkt.set_all_pixels_brightness(0.1);

```
loop {
    for n in 0..8 {
        blinkt.set_pixel(n, rng.gen::<u8>(), rng.gen::<u8>(), rng.gen::<u8>());
    }
    blinkt.show();

    thread::sleep(Duration::from_millis(50));
}
```

}

```

From: 
https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md

`
MOSI    P1-19
MISO    P1-21
SCLK    P1-23   P1-24    CE0
GND     P1-25   P1-26    CE1
`
```

**Comment by golemparts** [comment]
Could you give it a try with DAT 9 and CLK 11? 21 and 23 are the physical locations on the 2x20 header, while Blinkt uses the BCM pin numbers.

**Comment by golemparts** [comment]
Here's a good reference for physical pin locations (in gray) versus the BCM GPIO numbering (in orange) used by Blinkt. As you can see, MISO and SCLK for SPI0 are BCM 9 and 11:
![rp2_pinout](https://cloud.githubusercontent.com/assets/9930578/20121114/067df146-a610-11e6-8db0-946b1a5d7191.png)

**Comment by bo01ean** [comment]
That makes sense! Will give it a shot tonight, thanks!

**Comment by bo01ean** [comment]
ok, the pin mapping was def the issue, thank you!
