### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by hellow554** [golemparts/blinkt#6]
Hey ho!

I would like to see a new version on crates.io because of 77a5cdd0a755ac57f3372b8fde79fc187b3f9f07 and f0413795c22a69f91828e648bea3d0f3e31050b8

Thanks a lot!

**Comment by hellow554** [comment]
ping @golemparts ❤️

**Comment by hellow554** [comment]
ping @golemparts ❤️

**Comment by golemparts** [comment]
Thanks for the ping and sorry for the lack of response. I'll get a new release out in the next few days.

**Comment by golemparts** [comment]
0.7.0 is now available on crates.io 😄
